name: Release build
on: [workflow_dispatch]

jobs:
  build:
    name: Release build
    runs-on: windows-2022
    steps:
      - name: Delete components
        run: |
                Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
                $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
                $componentsToRemove= @(
                    "Microsoft.VisualStudio.Component.VC.ATLMFC"
                    "Microsoft.VisualStudio.Component.VC.ATLMFC.Spectre"                   
                )
                [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --remove " +  $_}
                $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
                # should be run twice
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
      
      - name: Install components
        run: |
                Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
                $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
                $componentsToRemove= @(
                  "Microsoft.VisualStudio.Component.VC.14.29.16.11.MFC"
                  "Microsoft.VisualStudio.Component.VC.14.29.16.11.MFC.Spectre"
                  "Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL"
                  "Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL.Spectre"
                )
                [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --add " +  $_}
                $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
                # should be run twice
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install third party libraries
        run: ./InstallThirdPartyLibraries.ps1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild /m CppCoverage.sln /p:Configuration=Release /p:Platform=x64

      - name: Build MSI
        run: msbuild /p:Configuration=Release OpenCppCoverage.wixproj

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MSI
          path: bin/Release/OpenCppCoverage.msi
            
